15-django/productly/productly/urls.py
from django.contrib import admin
from django.urls import path, include 
from . import views


urlpatterns = [
    path('', views.inicio, name="inicio"),
    path('admin/', admin.site.urls),
    path('productos/', include('productos.urls'))
]

15-django/productly/productos/urls.py
from django.urls import path
from . import views


app_name = 'productos'

urlpatterns = [
    path('', views.index, name='index'),
    path('formulario', views.formulario, name= 'formulario'),
    path('<int:producto_id>', views.detalle, name= 'detalle'), #name='producto_detalle'),
]

15-django/productly/productos/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=100) #longuitud maxima 100 que debe guardar

    def __str__(self):
        return self.nombre
    
class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    stock = models.IntegerField()
    puntaje = models.FloatField()
    #CASCADE: ELIMINAR EL PRODUCTO
    # PROTECT: LANZA UN ERROR
    # RESTRICT: SOLO ELIMINA SI NO EXISTEN PRODUCTOS
    # SET_NULL: ACTUALIZA EL VALOR
    # SET_DEFAULT: ASIGAN VAL POR DEFECTO
    categoria = models.ForeignKey(
        Categoria, on_delete=models.CASCADE
    )
    creado_en = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.nombre

15-django/productly/productos/forms.py
from . import models
from django.forms import ModelForm

class ProductoForm(ModelForm):
    class Meta:
        model = models.Producto
        fields = ['nombre', 'stock', 'puntaje', 'categoria']

15-django/productly/productly/views.py
from django.shortcuts import render

def inicio(request):
    return render(
        request, 
        'inicio.html',


    )

15-django/productly/productos/views.py
from django.http import Http404, HttpResponse, HttpResponseRedirect #, JsonResponse
from django.shortcuts import render, get_object_or_404

from .forms import ProductoForm
from .models import Producto
#productos

# Create your views here.
def index(request):
    productos = Producto.objects.all() # si quetremos ver en un json debemos usar values()

    return render(
        request, 
        'index.html',
        context={'productos':productos}
    )


def detalle(request, producto_id):
    producto =  get_object_or_404(Producto, id=producto_id)
    producto= Producto.objects.get(id=producto_id)
    return render(
        request, 
        'detalle.html',
        context={'producto':producto})

def formulario(request): # GET y POST esto es un formulario
    if request.method == 'POST':
        form = ProductoForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/productos')
    else:
        form = ProductoForm()

    return render (
        request,
        'producto_form.html',
        {'form': form}
    )






# # print(productos)
 # return JsonResponse(list(productos), safe=False) # si no es un diccionario poner safe en false 

15-django/productly/productos/templates/detalle.html
{%extends 'base.html'%}

{%block content%}
    <div>
        <h2>{{ producto.nombre }}</h2>
        <p>{{producto.categoria}}</p>
        <p>{{producto.stock}}</p>
        <p>{{producto.puntaje}}</p>
        <p>{{producto.creado_en}}</p>
    </div>

{%endblock%}

15-django/productly/productos/templates/index.html
{%extends 'base.html' %} 
{%block content%}
        
    
<h1> Productos</h1>
<a href= {% url "productos:formulario" %}> NUevo pruducto </a>

<table class="table">
    <thead>
        <tr>
            
            <th>Nombre</th>
            <th>stock</th>
            <th>puntaje</th>
            <th>categoria</th>
        </tr>
    </thead>
    <tbody>
        {%for producto in productos%}
        <tr>
            <td>
                <a href="{% url 'productos:detalle' producto.id %}">
                    {{ producto.nombre}}

                </a>
            </td>
            <td>{{ producto.stock}}</td>
            <td>{{ producto.puntaje}}</td>
            <td>{{ producto.categoria}}</td>
        </tr>
        {%endfor%}
    </tbody>
</table>
{%endblock%}

15-django/productly/productos/templates/producto_form.html
{%extends 'base.html'%}
{%block content%}
<form 
    novalidate
    action="{% url 'productos:formulario' %}"
    method='post'>
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Enviar"/>
</form>
{%endblock%}

15-django/productly/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>productly</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
  
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href=" {% url "inicio" %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "productos:index" %}">Productos</a>
        </li>
        
      </ul>
    </div>
  </div>
</nav>
    <div class="container ">
        {%block content%}

        {%endblock%}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>

</body>
</html>

15-django/productly/templates/django/forms/label.html
{% if use_tag %}<{{ tag }}{% include 'django/forms/attrs.html' %}class ="form-label">{{ label }}</{{ tag }}>{% else %}{{ label }}{% endif %}

15-django/productly/templates/django/forms/widgets/input.html
<input 
class = "form-control {{widget.attrs.class}}"
    type="{{ widget.type }}" 
    name="{{ widget.name }}"{% if widget.value != None %} 
    value="{{ widget.value|stringformat:'s' }}"{% endif %}{% include "django/forms/widgets/attrs.html" %}
    
> 

15-django/productly/templates/django/forms/widgets/select.html
<select class="form-select" name="{{ widget.name }}"{% include "django/forms/widgets/attrs.html" %}>{% for group_name, group_choices, group_index in widget.optgroups %}{% if group_name %}
  <optgroup label="{{ group_name }}">{% endif %}{% for option in group_choices %}
  {% include option.template_name with widget=option %}{% endfor %}{% if group_name %}
  </optgroup>{% endif %}{% endfor %}
</select>

15-django/productly/templates/form_snippet.html
{%load add_attr%}

{% for field in form %}
    <div class="mb-3">
        {{ field.label_tag }} 
        {%if field.errors%}
            {{field |add_attr:"class:is-invalid"}}
        {%else%}
            {{field}}
        {%endif%}
        <div id="validationServer03Feedback" class="invalid-feedback">
            {% for error in field.errors %} 
                {{ error }}
            {% endfor %}
        </div>
    </div>
{% endfor %}

15-django/productly/templates/inicio.html
{% extends "base.html" %}

{% block content %} 
    hola mundo of 🅥🅔🅣🅓🅨⓪③
{% endblock content %} 